"""Initial VM request table

Revision ID: 1c64dac73974
Revises: 
Create Date: 2025-12-15 16:25:02.535113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c64dac73974'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.String(length=255), nullable=False),
    sa.Column('requester_username', sa.String(length=255), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=63), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Enum('IPRAKTIKUM', 'THESIS', 'CHAIR_PROJECT', name='projecttype'), nullable=False),
    sa.Column('project_details', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('resource_justification', sa.Text(), nullable=True),
    sa.Column('default_ports_enabled', sa.Boolean(), nullable=False),
    sa.Column('additional_ports', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('additional_users', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ssh_key_type', sa.String(length=20), nullable=False),
    sa.Column('ssh_key_value', sa.Text(), nullable=True),
    sa.Column('additional_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', name='requeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('jira_ticket_key', sa.String(length=50), nullable=True),
    sa.Column('gitlab_project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_requests_requester_id'), 'vm_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vm_requests_requester_id'), table_name='vm_requests')
    op.drop_table('vm_requests')
    # ### end Alembic commands ###
