"""add_vm_access_requests_table

Revision ID: fcad15d0cf82
Revises: ded0f26130b7
Create Date: 2025-12-17 14:28:36.564792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcad15d0cf82'
down_revision: Union[str, None] = 'ded0f26130b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_access_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.String(length=255), nullable=False),
    sa.Column('requester_username', sa.String(length=255), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('hostname', sa.String(length=63), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('ssh_key_type', sa.String(length=20), nullable=False),
    sa.Column('ssh_key_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='accessrequeststatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('jira_ticket_key', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_access_requests_hostname'), 'vm_access_requests', ['hostname'], unique=False)
    op.create_index(op.f('ix_vm_access_requests_requester_id'), 'vm_access_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vm_access_requests_requester_id'), table_name='vm_access_requests')
    op.drop_index(op.f('ix_vm_access_requests_hostname'), table_name='vm_access_requests')
    op.drop_table('vm_access_requests')
    # ### end Alembic commands ###
