apiVersion: v1
kind: Service
metadata:
  name: {{ include "aet-request.client.fullname" . }}
  labels:
    {{- include "aet-request.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "aet-request.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: client
