{{- if .Values.client.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aet-request.client.fullname" . }}
  labels:
    {{- include "aet-request.labels" . | nindent 4 }}
    app.kubernetes.io/component: client
spec:
  minAvailable: {{ .Values.client.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "aet-request.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: client
{{- end }}
