apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aet-request.server.fullname" . }}
  labels:
    {{- include "aet-request.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  DATABASE_URL: {{ include "aet-request.databaseUrl" . | quote }}
  JIRA_USERNAME: {{ .Values.server.secrets.jiraUsername | quote }}
  JIRA_API_TOKEN: {{ .Values.server.secrets.jiraApiToken | quote }}
  REDMINE_API_KEY: {{ .Values.server.secrets.redmineApiKey | quote }}
  GITLAB_TOKEN: {{ .Values.server.secrets.gitlabToken | quote }}
