apiVersion: v2
name: aet-request
description: Helm chart for the AET Request application
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: 15.5.38
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
